name: 'tpch_pipeline'
version: '1.0.0'
config-version: 2

profile: 'tpch'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets:
  - "target"

models:
  tpch_pipeline:
    staging:
      +materialized: view
    marts:
      +materialized: table
      +file_format: iceberg
